all: src/main.go src/network.go src/checkers.go src/fuzzer.go src/config.go
	go build src/main.go src/network.go src/checkers.go src/fuzzer.go src/config.go
reducer: src/reducer.go src/network.go src/config.go
	go build src/reducer.go src/network.go src/config.go
reduce_script: src/reduce_script.go src/checkers.go src/config.go
	go build src/reduce_script.go src/checkers.go src/config.go
